language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_USERNAME/movies-neo4j" .;
    else
    docker build -t "$DOCKER_USERNAME/movies-neo4j:$TRAVIS_BRANCH" .;
    fi
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push "$DOCKER_USERNAME/movies-neo4j:latest";
    else
    docker push "$DOCKER_USERNAME/movies-neo4j:$TRAVIS_BRANCH";
    fi